#!/bin/bash

#!/bin/bash

# Skript küsib kasutajalt ridade ja tärnide arvu
read -p "Sisesta ridade arv: " ridade_arv
read -p "Sisesta tarnide arv reas: " tarnide_arv

# Välisilmega kontrollime ridu
for ((i=1; i<=ridade_arv; i++))
do
  # Sisemise silmusega kontrollime tärnide arvu igas reas
  for ((j=1; j<=tarnide_arv; j++))
  do
    # Väljastame tärni ilma uuele reale minemata
    echo -n "* "
  done
  # Lisame uue rea
  echo
done

