#!/bin/bash

# Kontrolli, kas on antud õige arv parameetreid
if [ $# -ne 2 ]; then
    echo "Kasutusjuhend: $0 kasutajad_fail paroolid_fail"
    exit 1
fi

kasutajad_fail="$1"
paroolid_fail="$2"

# Kontrolli, kas failid eksisteerivad
if [ ! -f "$kasutajad_fail" ] || [ ! -f "$paroolid_fail" ]; then
    echo "Üks või mõlemad failid ei leitud."
    exit 1
fi

# Loe kasutajate failist ja paroolide failist vastavad read
while IFS= read -r kasutajanimi || [ -n "$kasutajanimi" ]; do
    IFS= read -r parool <&3

    echo "Lisan kasutaja: $kasutajanimi"

    # Kontrolli, kas kasutaja on juba olemas
    if sudo id "$kasutajanimi" &>/dev/null; then
        echo "Kasutaja nimega $kasutajanimi on juba olemas."
    else
        # Kasuta sudo useradd käsku vajalike võtmetega
        sudo useradd "$kasutajanimi" -m -s /bin/bash

        # Kontrolli, kas kasutaja lisamine oli edukas
        if [ $? -eq 0 ]; then
            echo "Kasutaja nimega $kasutajanimi on lisatud süsteemi."

            # Lisa vajalikud failid kodukataloogi struktuuri
            sudo cp -r /etc/skel/. "/home/$kasutajanimi/"

            # Lisa kasutajale parool shadow faili sisse
            sudo usermod -p "$(openssl passwd -1 "$parool")" "$kasutajanimi"

            echo "Parool lisatud kasutajale $kasutajanimi."

            # Näita kasutajainfo
            sudo id "$kasutajanimi"
            sudo ls -la "/home/$kasutajanimi"
        else
            echo "Probleem kasutaja $kasutajanimi lisamisega."
            echo "Probleemi kood on $?."
        fi
    fi

    echo "-------------------------"
done < "$kasutajad_fail" 3< "$paroolid_fail"

